searchtweet.tdm.tfidf1 <- tdm.TFIDF(searchtweet.clean[1:1000,])
searchtweet.tdm.tfidf2 <- tdm.TFIDF(searchtweet.clean[1:2000,])
searchtweet.tdm.tfidf3 <- tdm.TFIDF(searchtweet.clean[1:3000,])
searchtweet.tdm.tfidf4 <- tdm.TFIDF(searchtweet.clean[1:4000,])
searchtweet.tdm.tfidf5 <- tdm.TFIDF(searchtweet.clean[1:5000,])
searchtweet.tdm.tfidf6 <- tdm.TFIDF(searchtweet.clean[1:6000,])
searchtweet.tdm.tfidf7 <- tdm.TFIDF(searchtweet.clean[1:7000,])
searchtweet.tdm.tfidf8 <- tdm.TFIDF(searchtweet.clean[1:8000,])
searchtweet.tdm.tfidf9 <- tdm.TFIDF(searchtweet.clean[1:9000,])
searchtweet.tdm.tfidf10 <- tdm.TFIDF(searchtweet.clean)

tfidf.matrix1 <- as.matrix(searchtweet.tdm.tfidf1)
tfidf.matrix2 <- as.matrix(searchtweet.tdm.tfidf2)
tfidf.matrix3 <- as.matrix(searchtweet.tdm.tfidf3)
tfidf.matrix4 <- as.matrix(searchtweet.tdm.tfidf4)
tfidf.matrix5 <- as.matrix(searchtweet.tdm.tfidf5)
tfidf.matrix6 <- as.matrix(searchtweet.tdm.tfidf6)
tfidf.matrix7 <- as.matrix(searchtweet.tdm.tfidf7)
tfidf.matrix8 <- as.matrix(searchtweet.tdm.tfidf8)
tfidf.matrix9 <- as.matrix(searchtweet.tdm.tfidf9)
tfidf.matrix10 <- as.matrix(searchtweet.tdm.tfidf10)

word_freqs1 <- sort(colSums(tfidf.matrix1), decreasing = TRUE)
word_freqs2 <- sort(colSums(tfidf.matrix2), decreasing = TRUE)
word_freqs3 <- sort(colSums(tfidf.matrix3), decreasing = TRUE)
word_freqs4 <- sort(colSums(tfidf.matrix4), decreasing = TRUE)
word_freqs5 <- sort(colSums(tfidf.matrix5), decreasing = TRUE)
word_freqs6 <- sort(colSums(tfidf.matrix6), decreasing = TRUE)
word_freqs7 <- sort(colSums(tfidf.matrix7), decreasing = TRUE)
word_freqs8 <- sort(colSums(tfidf.matrix8), decreasing = TRUE)
word_freqs9 <- sort(colSums(tfidf.matrix9), decreasing = TRUE)
word_freqs10 <- sort(colSums(tfidf.matrix10), decreasing = TRUE)
# create a data frame with words and their frequencies
dm1 <- data.frame(word = names(word_freqs1), freq = word_freqs1)
dm2 <- data.frame(word = names(word_freqs2), freq = word_freqs2)
dm3 <- data.frame(word = names(word_freqs3), freq = word_freqs3)
dm4 <- data.frame(word = names(word_freqs4), freq = word_freqs4)
dm5 <- data.frame(word = names(word_freqs5), freq = word_freqs5)
dm6 <- data.frame(word = names(word_freqs6), freq = word_freqs6)
dm7 <- data.frame(word = names(word_freqs7), freq = word_freqs7)
dm8 <- data.frame(word = names(word_freqs8), freq = word_freqs8)
dm9 <- data.frame(word = names(word_freqs9), freq = word_freqs9)
dm10 <- data.frame(word = names(word_freqs10), freq = word_freqs10)

plot(log(1:nrow(dm1)),log(dm1$freq),type = "l")
points(x = log(1:nrow(dm2)),log(dm2$freq),type = "l")
points(x = log(1:nrow(dm3)),log(dm3$freq),type = "l")
points(x = log(1:nrow(dm4)),log(dm4$freq),type = "l")
points(x = log(1:nrow(dm5)),log(dm5$freq),type = "l")
points(x = log(1:nrow(dm6)),log(dm6$freq),type = "l")
points(x = log(1:nrow(dm7)),log(dm7$freq),type = "l")
points(x = log(1:nrow(dm8)),log(dm8$freq),type = "l")
points(x = log(1:nrow(dm9)),log(dm9$freq),type = "l")
points(x = log(1:nrow(dm10)),log(dm10$freq),type = "l")

plot(log(1:nrow(dm10)),log(dm10$freq),type = "l",xlab = "log of rank",ylab = "log of term frequency",main = "Zipf's plot")
points(x = log(1:nrow(dm9)),log(dm9$freq),type = "l", col = "red")
points(x = log(1:nrow(dm8)),log(dm8$freq),type = "l", col = "blue")
points(x = log(1:nrow(dm7)),log(dm7$freq),type = "l", col = "yellow")
points(x = log(1:nrow(dm6)),log(dm6$freq),type = "l", col = "orange")
points(x = log(1:nrow(dm5)),log(dm5$freq),type = "l", col = "pink")
points(x = log(1:nrow(dm4)),log(dm4$freq),type = "l", col = "green")
points(x = log(1:nrow(dm3)),log(dm3$freq),type = "l", col = "gray")
points(x = log(1:nrow(dm2)),log(dm2$freq),type = "l", col = "magenta")
points(x = log(1:nrow(dm1)),log(dm1$freq),type = "l", col = "cyan")

plot(x = 1:nrow(dm10),y=dm10$freq,type = "l")
points(x = 1:nrow(dm9),y=dm9$freq,type = "l",col = "red")
points(x = 1:nrow(dm8),y=dm8$freq,type = "l",col = "blue")
points(x = 1:nrow(dm7),y=dm7$freq,type = "l",col = "yellow")
points(x = 1:nrow(dm6),y=dm6$freq,type = "l",col = "orange")
points(x = 1:nrow(dm5),y=dm5$freq,type = "l",col = "pink")
points(x = 1:nrow(dm4),y=dm4$freq,type = "l",col = "green")
points(x = 1:nrow(dm3),y=dm3$freq,type = "l",col = "gray")
points(x = 1:nrow(dm2),y=dm2$freq,type = "l",col = "magenta")
points(x = 1:nrow(dm1),y=dm1$freq,type = "l",col = "cyan")

Zipf_plot(searchtweet.tdm.tfidf1)